name: kwplayer 
version: '0.1'
summary: kwplayer
description: |
  This is kwplayer snap application. kwplayer is a music player.

grade: stable 
confinement: devmode 

apps:
  kwplayer:
    command: desktop-launch $SNAP/bin/kwplayer
    plugs:
      - network
      - unity7
      - x11
      - home
      - opengl
      - pulseaudio

parts:
  app:
    source: ./src
    plugin: python3

    build-packages:
      - hicolor-icon-theme
    stage-packages:
      - gir1.2-gtk-2.0
      - gir1.2-gtk-3.0
      - gir1.2-gtk-3.0:amd64
      - gir1.2-gtksource-3.0
      - gir1.2-notify-0.7
      - gir1.2-gstreamer-1.0
      - gir1.2-gst-plugins-base-1.0
      - libcanberra-gtk3-module
      - gstreamer1.0-libav
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gnome-icon-theme-symbolic
      - libnotify4
      - software-center  
      - python3-cairo
      - python3-dbus
      - python3-gi
      - python3-gi-cairo
      - python3-html2text
      - python3-ply
      - python-dbus
      - python3-leveldb
      - fonts-wqy-zenhei
      - gir1.2-appindicator3-0.1
      - fcitx-frontend-gtk3
    after: [desktop-gtk3]
    
